version: '3'

services:
  app:
    depends_on:
      - mysql
    build:
      context: .
      args:
        options: --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - kanastra-network
  
  mysql:
    container_name: mysql
    build: ./mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - ./mysql/local.env
    tty: true
    networks:
      - kanastra-network
  
networks:
  kanastra-network:
    driver: bridge